### ISSUE TITLE
TestReceiveAV example doesn't work on AWS EC2 Windows Instance

### ISSUE THREAD

**Issue by davyloots** [microsoft/MixedReality-WebRTC#266]
The TestReceiveAV example works on my development machine, but on a T3.Medium EC2 Instance running Windows Server 2019, I'm getting the following exception when a connection is established:
`System.InvalidOperationException: Cannot invoke native method with invalid peer connection handle.
   at Microsoft.MixedReality.WebRTC.PeerConnection.ThrowIfConnectionNotOpen()
   at Microsoft.MixedReality.WebRTC.PeerConnection.SetRemoteDescription(String type, String sdp)
   at TestReceiveAV.Program.<>c__DisplayClass3_0.<MessageReceived>b__3(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at TestReceiveAV.Program.MessageReceived(WebRtcSession session, String msg)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

It looks like the Initialize call doesn't complete successfully, but I can't figure out why not.

**Comment by djee-ms** [comment]
Hi @davyloots,

I had a look at the TestReceiveAV code and I see that the continuation task does not check if the initialization succeeded:

https://github.com/microsoft/MixedReality-WebRTC/blob/843c7dbc28cb7f2f6aa1354d4368f7ddf044b099/examples/TestReceiveAV/Program.cs#L122-L132

I'd try to check for `t.Exception` inside the continuation task, or add some `TaskContinuationOptions.OnlyOnRanToCompletion` option to that continuation task. To be fair since there's an `await` already there's no reason to use a continuation task.

As for why it's failing, does that EC2 instance have access to both a webcam and microphone? The video module is somewhat resilient but the default Google audio module is very picky and will fail the entire WebRTC initializing if any audio device fails to initialize, and I think also if there's no audio device (can't remember that one for sure on top of my head).

**Comment by davyloots** [comment]
Thank you for the quick response!

Yes, the Initialize call not succeeding is the actual problem. 
Thank you for the tip on the webcam/microphone. The server doesn't actually have an audio recording device so that's probably why it fails. I didn't expect it to need one. I've been looking for hours for ways to create a virtual microphone on the EC2 instance, but it appears virtually impossible. But at least now I why it doesn't work. 

If I find a way to create a virtual microphone on the server, I'll update the issue. Thanks again!

**Comment by djee-ms** [comment]
Yes this is a problem many users have and we want to fix, the code shouldn't require an audio device to be present. Unfortunately that's deep inside Google's code so not easy for us to make a change, as we are consuming WebRTC UWP which is in turn consuming the webrtc.org repo.

**Comment by djee-ms** [comment]
The virtual microphone might not be necessary, I think only the output audio device is.

**Comment by davyloots** [comment]
There actually is an audio input and output device now - albeit a virtual one. Unfortunately still the same error. I wish there was a way to get some logging out of the Google webRTC library to at least have an idea of what's going on.

**Comment by djee-ms** [comment]
You can maybe use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) from SysInternals, if that runs on the instance. It's a small tool that registers as a debugger (but is not a debugger) and allows you to see the debug logs that are usually sent when a debugger is attached. WebRTC should output some logs through that.

**Comment by davyloots** [comment]
Fixed! I can't believe I'm so stupid. Before copying the app to the server, I did a dotnet publish. Of course this doesn't copy over the native dll's. So I was simply missing Microsoft.MixedReality.WebRTC.Native.dll.
Thanks again for your responses. I'm sorry to bother you with this. Maybe somebody in the future will make the same mistake and come across this post.

**Comment by djee-ms** [comment]
Hi @davyloots, no problem, glad it's fixed. It's unfortunate our logging is not better. Did you manage to use DebugView? How did you catch the issue? Just for future reference, and to see how we could improve things to catch this error more easily.

**Comment by djee-ms** [comment]
I logged #266 to improve DLL not found logging.

**Comment by davyloots** [comment]
> Hi @davyloots, no problem, glad it's fixed. It's unfortunate our logging is not better. Did you manage to use DebugView? How did you catch the issue? Just for future reference, and to see how we could improve things to catch this error more easily.

DebugView didn't give me any logging for this app (not on my development machine either). I had already tried ProcMon earlier, which gives at least an idea on registry keys being read, and I did notice that on my dev pc it started reading a lot of registry keys related to audiodevices, which was not the case on the server, but I couldn't figure out why.

I only found out by accident when I started thinking about changing out the native dll's for another version, noticing there wasn't one to begin with. I've had missing native libraries before, but they've always resulted into uncaught exceptions. This one didn't, so improved error reporting would definitely help.

Thanks again!
