### ISSUE TITLE
PeerConnection.RemoveDataChannel throws.  Unable to exit process when DataChannel is open.

### ISSUE THREAD

**Issue by lucent-sea** [microsoft/MixedReality-WebRTC#523]
**Describe the bug**
(Thanks for all your work on this library!)

Using .NET Core 3.1 in both console and WPF apps, the process can't exit if there's an open DataChannel.  Prior to the 2.0 update, I'd call `DataChannel.Dispose()` and `PeerConnect.Dispose()` on all connections prior to exiting, and the process closed fine.

It looks like the way to dispose of the DataChannel now is through `PeerConnection.RemoveDataChannel()`.  This, however, is throwing "Handle is not initialized."

I'm able to wrap this in a try/catch, though, and the process still exits.

Here's the stack trace: 

```
   at System.ThrowHelper.ThrowInvalidOperationException_HandleIsNotInitialized()
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at Microsoft.MixedReality.WebRTC.Interop.Utils.ReleaseWrapperRef(IntPtr wrapperRef)
   at Microsoft.MixedReality.WebRTC.DataChannel.DestroyNative()
   at Microsoft.MixedReality.WebRTC.PeerConnection.RemoveDataChannel(DataChannel dataChannel)
```

**To Reproduce**
1. Start a PeerConnection with a DataChannel connected.
2. Try calling PeerConnection.RemoveDataChannel.

**Expected behavior**
PeerConnection.RemoveDataChannel should dispose of the DataChannel without throwing.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Environment**
_Please fill the information for **each peer** if different_
 - MR-WebRTC version (package version, or specific commit if building from source)
    - The 2.0 NuGet package.
 - Platform: [e.g. Windows Desktop, UWP, Unity Editor, Unity Android Player, Unity Standalone Player (Windows Desktop), Unity WSA Player (UWP)]
    - Windows Desktop.  .NET Core 3.1.
 - Architecture: [e.g. x86, x64, ARM, ARM64; Unity Editor is x64 on Windows]
    - x64
 - Unity version (if applicable): [e.g. 2018.4, 2019.1]
 - Target device: [e.g. Windows Desktop, HoloLens 1, HoloLens 2, Android Phone]
   - Windows Desktop

**Additional context**
_Add any other context about the problem here._

**Comment by lucent-sea** [comment]
Maybe it was something I was doing, but the process is exiting properly now.
